version: '3.8'

services:
  ui:
    build:
      context: ./ui
    ports:
      - "5000:5000"

  task-service:
    build:
      context: ./services
    ports:
      - "5001:5001"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
