services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    environment:
      - PORT=5000
    volumes:
      - ./data:/app/db  # Monta ./data do host em /app/db no container

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    environment:
      - PORT=5001
    volumes:
      - ./data:/app/db  # Monta ./data do host em /app/db no container

  app3:
    image: busybox:latest
    container_name: app3
    volumes:
      - ./backup:/var/www  # Monta o diretório app3 como raiz do servidor
    command: ["httpd", "-f", "-p", "3000", "-h", "/var/www"]  # Inicia o httpd na porta 3000
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3